# Using numpy generate a matrix of size 20X5 containing random numbers drawn uniformly from the range of 1 to 2. Using Pandas create a dataframe out of this matrix. Name the columns of the dataframe as “a”, “b”, “c”, “d”, “e”. Find the column with the highest standard deviation. Find the row with the lowest mean.

In [11]:
import numpy as np
import pandas as pd
import random
arr=np.empty((20,5))
for i in arr:
    for j in range(len(i)):
        i[j]=1+random.random()
print(arr)
df=pd.DataFrame(arr,columns = ['a','b','c','d','e'])
print(df)

print(df.std(ddof=0))
print(df.mean(axis=1))

[[1.83959173 1.01465754 1.78197943 1.8894884  1.36272483]
 [1.23680971 1.98324293 1.88464717 1.36787198 1.20678821]
 [1.07139477 1.19873513 1.02881696 1.96981228 1.70503905]
 [1.15589672 1.59101071 1.350197   1.50162824 1.82010409]
 [1.57254705 1.24654182 1.77314822 1.30356438 1.88693485]
 [1.15025419 1.01547521 1.31078978 1.37399778 1.87416474]
 [1.39000146 1.98276303 1.34638038 1.87691323 1.48325424]
 [1.09872641 1.63027946 1.65700666 1.33838203 1.65305957]
 [1.99536595 1.47984715 1.75958927 1.98489333 1.87026414]
 [1.5000591  1.08532137 1.04835756 1.0846806  1.42356105]
 [1.79641952 1.27960678 1.13388263 1.31325532 1.3245376 ]
 [1.8021316  1.35218344 1.94356257 1.16510651 1.7625859 ]
 [1.34579749 1.50975454 1.60245339 1.68780128 1.65452935]
 [1.7561941  1.20415787 1.27240054 1.35732447 1.06569805]
 [1.06112163 1.49546226 1.44461152 1.77666795 1.50676903]
 [1.36159416 1.47400517 1.94906118 1.07464482 1.42514923]
 [1.36654486 1.13990146 1.31639306 1.83066005 1.57944154]
 [1.99253951 1

Column with highest standard deviation is c and row with lowest mean is index 9.

# Add a new column to the dataframe called “f” which is the sum of the columns “a”, “b”, “c”, “d”, “e”. Create another column called “g”. The value in the column “g” should be “LT8” if the value in the column “f” is less than 8 and “GT8” otherwise. Find the number of rows in the dataframe where the value in the column “g” is “LT8”. Find the standard deviation of the column “f” for the rows where the value in the column “g” is “LT8” and “GT8” respectively.

In [16]:
import numpy as np
import pandas as pd
arr=np.array(
 [[1.83959173,1.01465754,1.78197943,1.8894884,1.36272483],
 [1.23680971,1.98324293,1.88464717,1.36787198,1.20678821],
 [1.07139477,1.19873513,1.02881696,1.96981228,1.70503905],
 [1.15589672,1.59101071,1.350197,  1.50162824,1.82010409],
 [1.57254705,1.24654182,1.77314822,1.30356438,1.88693485],
 [1.15025419,1.01547521,1.31078978,1.37399778,1.87416474],
 [1.39000146,1.98276303,1.34638038,1.87691323,1.48325424],
 [1.09872641,1.63027946,1.65700666,1.33838203,1.65305957],
 [1.99536595,1.47984715,1.75958927,1.98489333,1.87026414],
 [1.5000591, 1.08532137,1.04835756,1.0846806, 1.42356105],
 [1.79641952,1.27960678,1.13388263,1.31325532,1.3245376 ],
 [1.8021316, 1.35218344,1.94356257,1.16510651,1.7625859],
 [1.34579749,1.50975454,1.60245339,1.68780128,1.65452935],
 [1.7561941, 1.20415787,1.27240054,1.35732447,1.06569805],
 [1.06112163,1.49546226,1.44461152,1.77666795,1.50676903],
 [1.36159416,1.47400517,1.94906118,1.07464482,1.42514923],
 [1.36654486,1.13990146,1.31639306,1.83066005,1.57944154],
 [1.99253951,1.14112754,1.11181586,1.57452817,1.67163663],
 [1.41553373,1.71598837,1.23679985,1.8915394, 1.85046196],
 [1.08433661,1.56334271,1.96081913,1.90014628,1.54161377]]) #from previous question
df=pd.DataFrame(arr,columns = ['a','b','c','d','e'])
df = df.assign(f=df['a'] + df['b'] + df['c'] + df['d'] + df['e'])
df=df.assign(g = df['f'].apply(lambda x: "LT8" if x < 8 else "GT8"))
print(df)
print(f"LT8: {df.loc[df['g'] == 'LT8', 'f'].std()}")
print(f"GT8: {df.loc[df['g'] == 'GT8', 'f'].std()}")

           a         b         c         d         e         f    g
0   1.839592  1.014658  1.781979  1.889488  1.362725  7.888442  LT8
1   1.236810  1.983243  1.884647  1.367872  1.206788  7.679360  LT8
2   1.071395  1.198735  1.028817  1.969812  1.705039  6.973798  LT8
3   1.155897  1.591011  1.350197  1.501628  1.820104  7.418837  LT8
4   1.572547  1.246542  1.773148  1.303564  1.886935  7.782736  LT8
5   1.150254  1.015475  1.310790  1.373998  1.874165  6.724682  LT8
6   1.390001  1.982763  1.346380  1.876913  1.483254  8.079312  GT8
7   1.098726  1.630279  1.657007  1.338382  1.653060  7.377454  LT8
8   1.995366  1.479847  1.759589  1.984893  1.870264  9.089960  GT8
9   1.500059  1.085321  1.048358  1.084681  1.423561  6.141980  LT8
10  1.796420  1.279607  1.133883  1.313255  1.324538  6.847702  LT8
11  1.802132  1.352183  1.943563  1.165107  1.762586  8.025570  GT8
12  1.345797  1.509755  1.602453  1.687801  1.654529  7.800336  LT8
13  1.756194  1.204158  1.272401  1.357324  1.06