# Write a small piece of code to explain broadcasting in numpy.

Broadcasting in numpy arrays is done to operate between arrays of different dimensions. Usually they have the same dimension and otherwise the operation is undefined but in special cases, numpy broadcasts the arrays to produce a valid results.

In [2]:
import numpy as np
a=np.array([[1,2,3],
            [7,4,2],
            [8,2,1]])
b=np.array([3])
c=np.array([6,9,2])

print(f"a*b : \n{a*b}")
print(f"a+b : \n{a+b}")
print(f"b*c : \n{b*c}")
print(f"b+c : \n{b+c}")
print(f"a*c : \n{a*c}")
print(f"a+c : \n{a+c}")

a*b : 
[[ 3  6  9]
 [21 12  6]
 [24  6  3]]
a+b : 
[[ 4  5  6]
 [10  7  5]
 [11  5  4]]
b*c : 
[18 27  6]
b+c : 
[ 9 12  5]
a*c : 
[[ 6 18  6]
 [42 36  4]
 [48 18  2]]
a+c : 
[[ 7 11  5]
 [13 13  4]
 [14 11  3]]


However broadcasting between 2 arrays with different dimensions is only possible when the dimensions compared are equal or if one of them is unity, otherwise it gives an error

In [5]:
import numpy as np
a=np.array([[1,2,3],
            [7,4,2],
            [8,2,1]])
b=np.array([6,9,2],
           [1,4,5])

print(f"a*b : \n{a*b}")
print(f"a+b : \n{a+b}")

TypeError: Field elements must be 2- or 3-tuples, got '1'