# Q2 Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy.
# Compare the timing of both solutions. Which one is faster? Why?


In [26]:
import time
# a) Using List of Lists:

A = [[9,8,3,1,2,7,9,1,4,6,4],
     [6,5,2,0,9,4,1,6,3,2,3],
     [0,0,2,1,4,2,3,5,5,3,1]]

B = [[1,2,3],
     [4,5,6],
     [7,8,9],
     [1,0,1],
     [2,8,1],
     [4,5,6],
     [5,1,2],
     [1,5,7],
     [9,8,6],
     [1,5,6],
     [4,2,6]]

AB = [[0,0,0],
      [0,0,0],
      [0,0,0]]

start=time.time()

for a in range(len(A)): # Row-wise for Matrix 1
   for b in range(len(B[0])): # Column wise for Matrix 2
       for k in range(len(B)): # k times multiplication and consequently addition
           AB[a][b] = AB[a][b] + A[a][k] * B[k][b]

for ab in AB:
   print(ab)

print('\n')

print(f'Time: {time.time() - start}')


[199, 217, 256]
[126, 216, 191]
[103, 143, 130]


Time: 0.0012958049774169922


In [19]:
# b) using numpy array
import numpy as np

A = [[9,8,3,1,2,7,9,1,4,6,4],
     [6,5,2,0,9,4,1,6,3,2,3],
     [0,0,2,1,4,2,3,5,5,3,1]]

B = [[1,2,3],
     [4,5,6],
     [7,8,9],
     [1,0,1],
     [2,8,1],
     [4,5,6],
     [5,1,2],
     [1,5,7],
     [9,8,6],
     [1,5,6],
     [4,2,6]]

start=time.time()

print(np.matmul(A,B),'\n')

print(f'Time: {time.time() - start}')

[[199 217 256]
 [126 216 191]
 [103 143 130]] 

Time: 0.0006029605865478516


From the run time it is clear that the numpy timing is faster.

The reason being that how numpy treats its arrays vs how python treats its lists. Lists can have different data types and numpy arrays only has the same data type so that time is saved in evaluating the data type.

Another reason is that numpy carries out multiply operations parallely hence making it very fast in multiplying matrices.